brews:
  - tap:
      owner: screwdriver-cd
      name: meta-cli
    folder: Formula
    homepage: https://github.com/screwdriver-cd/meta-cli
    description: CLI for reading/writing Screwdriver project metadata
    install: |
      bin.install "meta-cli" => "meta"
    test: |
      system "#{bin}/meta-cli", "--version"
builds:
  - binary: meta
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
archives:
  - format: binary
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
