brews:
  - tap:
      owner: screwdriver-cd
      name: meta-cli
    folder: Formula
    homepage: https://github.com/screwdriver-cd/meta-cli
    description: CLI for reading/writing Screwdriver project metadata
    install: |
      bin.install File.basename(@stable.url) => "meta"
      ohai 'Notice', <<~EOL
        In order to use, you may wish to add the following to your ~/.bash_profile and execute now

          export SD_META_DIR="$HOME/meta"
          mkdir -p "$SD_META_DIR"

      EOL
    test: |
      system "#{bin}/meta-cli", "--version"
builds:
  - binary: meta
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
archives:
  - format: binary
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
