
shared:
    image: golang:1.22
    environment:
        GO111MODULE: on

jobs:
    main:
        environment:
            SD_SONAR_OPTS:  "-Dsonar.sources=./ -Dsonar.exclusions=**/*_test.go,**/vendor/** -Dsonar.tests=./ -Dsonar.test.inclusions=**/*_test.go -Dsonar.test.exclusions=**/vendor/** -Dsonar.go.coverage.reportPaths=${SD_ARTIFACTS_DIR}/coverage.out -Dsonar.go.tests.reportPaths=${SD_ARTIFACTS_DIR}/report.json"
        requires: [~commit, ~pr]
        steps:
            - goversion: go version
            - modverify: go mod verify
            - vet: go vet ./...
            - gofmt: (! gofmt -d . | grep '^')
            - test-setup: go install gotest.tools/gotestsum@latest
            - build: go build -a -o "${SD_ARTIFACTS_DIR}/meta"
            - link-meta-to-source: ln -s "${SD_ARTIFACTS_DIR}/meta" "${SD_SOURCE_DIR}/meta-cli"
            - test: gotestsum --format testname --jsonfile ${SD_ARTIFACTS_DIR}/report.json -- -coverprofile=${SD_ARTIFACTS_DIR}/coverage.out ./...
    publish:
        requires: [main]
        steps:
            - setup-ci: git clone https://github.com/screwdriver-cd/toolbox.git ci
            - tag: ./ci/git-tag.sh
            - release: "curl -sL https://git.io/goreleaser | bash"
        secrets:
            # Pushing tags to Git
            - GIT_KEY
            # Pushing releases to GitHub
            - GITHUB_TOKEN
