
shared:
    image: golang
    environment:
        GOPATH: /sd/workspace
        GO111MODULE: on

jobs:
    main:
        requires: [~pr, ~commit]
        steps:
            - goversion: go version
            - modverify: go mod verify
            - vet: go vet ./...
            - gofmt: (! gofmt -d . | grep '^')
            - test: go test ./...
            - build: go build -a -o $SD_ARTIFACTS_DIR/meta

    publish:
        requires: [main]
        steps:
            - setup-ci: git clone https://github.com/screwdriver-cd/toolbox.git ci
            - tag: ./ci/git-tag.sh
            - release: "curl -sL https://git.io/goreleaser | bash"
        secrets:
            # Pushing tags to Git
            - GIT_KEY
            # Pushing releases to GitHub
            - GITHUB_TOKEN
