# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MetaCli < Formula
  desc "CLI for reading/writing Screwdriver project metadata"
  homepage "https://github.com/screwdriver-cd/meta-cli"
  version "0.0.73"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/screwdriver-cd/meta-cli/releases/download/v0.0.73/meta-cli_darwin_arm64"
      sha256 "206f4de86d23642777c5583a5ef5ba3930f86dee7b4663c94d0a6cdd5e808fb3"

      def install
        bin.install File.basename(@stable.url) => "meta"
        ohai 'Notice', <<~EOL
          In order to use, you may wish to add the following to your ~/.bash_profile and execute now

            export SD_META_DIR="$HOME/meta"
            mkdir -p "$SD_META_DIR"

        EOL
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/screwdriver-cd/meta-cli/releases/download/v0.0.73/meta-cli_darwin_amd64"
      sha256 "d18008cde71aeda3d2cf9fd04e185f8cce1dd6b8cf97f01ec03df3c7e8324ba5"

      def install
        bin.install File.basename(@stable.url) => "meta"
        ohai 'Notice', <<~EOL
          In order to use, you may wish to add the following to your ~/.bash_profile and execute now

            export SD_META_DIR="$HOME/meta"
            mkdir -p "$SD_META_DIR"

        EOL
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/screwdriver-cd/meta-cli/releases/download/v0.0.73/meta-cli_linux_arm64"
      sha256 "289d33ffb3edacc11447719ade7b4114beee888786787fefcb26d4e3a096ab6d"

      def install
        bin.install File.basename(@stable.url) => "meta"
        ohai 'Notice', <<~EOL
          In order to use, you may wish to add the following to your ~/.bash_profile and execute now

            export SD_META_DIR="$HOME/meta"
            mkdir -p "$SD_META_DIR"

        EOL
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/screwdriver-cd/meta-cli/releases/download/v0.0.73/meta-cli_linux_amd64"
      sha256 "4b42f06a265359b8e57564179826c62b217e912925725290140179ee53146923"

      def install
        bin.install File.basename(@stable.url) => "meta"
        ohai 'Notice', <<~EOL
          In order to use, you may wish to add the following to your ~/.bash_profile and execute now

            export SD_META_DIR="$HOME/meta"
            mkdir -p "$SD_META_DIR"

        EOL
      end
    end
  end

  test do
    system "#{bin}/meta-cli", "--version"
  end
end
