# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Meta < Formula
  desc "CLI for reading/writing Screwdriver project metadata"
  homepage "https://github.com/screwdriver-cd/meta-cli"
  version "0.0.90"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/screwdriver-cd/meta-cli/releases/download/v0.0.90/meta-cli_darwin_amd64"
      sha256 "d8e864a196943a80b8e8a6db166d6b9acf806551adb6e4421eff3eda9c526354"

      define_method(:install) do
        bin.install File.basename(@stable.url) => "meta"
        ohai 'Notice', <<~EOL
          In order to use, you may wish to add the following to your ~/.bash_profile and execute now

            export SD_META_DIR="$HOME/meta"
            mkdir -p "$SD_META_DIR"

        EOL
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/screwdriver-cd/meta-cli/releases/download/v0.0.90/meta-cli_darwin_arm64"
      sha256 "b588db0d6a45044d3f9528a0df1dc878b19ddf0856ab2d3a63d56cb1ece3f371"

      define_method(:install) do
        bin.install File.basename(@stable.url) => "meta"
        ohai 'Notice', <<~EOL
          In order to use, you may wish to add the following to your ~/.bash_profile and execute now

            export SD_META_DIR="$HOME/meta"
            mkdir -p "$SD_META_DIR"

        EOL
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/screwdriver-cd/meta-cli/releases/download/v0.0.90/meta-cli_linux_amd64"
      sha256 "5017d2a8624adbddfacca8881f2994b8d7cf2225799e0b0f7960d5b8592295e1"
      define_method(:install) do
        bin.install File.basename(@stable.url) => "meta"
        ohai 'Notice', <<~EOL
          In order to use, you may wish to add the following to your ~/.bash_profile and execute now

            export SD_META_DIR="$HOME/meta"
            mkdir -p "$SD_META_DIR"

        EOL
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/screwdriver-cd/meta-cli/releases/download/v0.0.90/meta-cli_linux_arm64"
      sha256 "d7be09a5f84916e72e359c18470ac865ef52c3f42d1a2131f623c9007926cca9"
      define_method(:install) do
        bin.install File.basename(@stable.url) => "meta"
        ohai 'Notice', <<~EOL
          In order to use, you may wish to add the following to your ~/.bash_profile and execute now

            export SD_META_DIR="$HOME/meta"
            mkdir -p "$SD_META_DIR"

        EOL
      end
    end
  end

  test do
    system "#{bin}/meta-cli", "--version"
  end
end
